from typing import Final

RAW_FMT_O_UYY_E_VYY: Final[int] = ...
RAW_FMT_RGB565_LE: Final[int] = ...
RAW_FMT_BGR888: Final[int] = ...
RAW_FMT_VUY: Final[int] = ...
RAW_FMT_UYVY: Final[int] = ...

FRAME_TYPE_IDR: Final[int] = ...
FRAME_TYPE_I: Final[int] = ...
FRAME_TYPE_P: Final[int] = ...


class H264Encoder:
    def __init__(
        self,
        width: int,
        height: int,
        *,
        fps: int = 30,
        bitrate: int = 2_000_000,
        gop: int = 30,
        format: int = RAW_FMT_O_UYY_E_VYY,
        qp_min: int = 10,
        qp_max: int = 40,
    ) -> None:
        ...

    def encode(self, frame: bytes | bytearray | memoryview, pts: int = 0, /) -> bytes:
        ...

    def force_idr(self) -> None:
        ...

    def last_frame_type(self) -> int:
        ...

    def last_keyframe(self) -> bool:
        ...

    def close(self) -> None:
        ...